import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8');
const engine = read('../local-ai/engine.py');
const pipeline = read('../local-ai/audio_pipeline.py');
const enhancement = read('../local-ai/audio_enhancement.py');
const jobs = read('../local-ai/job_store.py');
const server = read('../local-ai/server.py');
const expoComputer = read('../expo-recorder/src/computer.js');
const audioDerivatives = read('../expo-recorder/src/audio-derivatives.js');
const expoStorage = read('../expo-recorder/src/storage.js');
const expoApp = read('../expo-recorder/App.js');
const phone = read('../lib/phone-transcription.ts');
const webDetail = read('../components/LectureDetail.tsx');
const transcriptionClient = read('../lib/transcription.ts');
const webDb = read('../lib/db.ts');
const launcher = read('../windows/lectureai-runtime.ps1');

assert.match(engine, /WINDOW_SECONDS = 300/);
assert.match(engine, /def plan_audio_windows/);
assert.match(engine, /class TranscriptionCancelled/);
assert.match(engine, /cancellation_check/);
assert.match(engine, /Preparing audio/);
assert.match(engine, /Combining transcript/);
assert.match(engine, /checkpoint_callback/);
assert.match(engine, /completed_audio_seconds/);
assert.match(engine, /_append_reconciled/);
assert.match(engine, /best_of=1/);
assert.doesNotMatch(engine, /task="translate"/);
assert.match(engine, /current_segments = source_segments/);
assert.match(engine, /condition_on_previous_text=False/);
assert.match(engine, /def quality_retry_plan/);
assert.match(engine, /\[\("strong", False\), \("balanced", True\), \("off", True\)\]/);
assert.match(engine, /def analyze_section_quality/);
assert.match(engine, /high-compression-ratio/);
assert.match(engine, /repeated-text-loop/);
assert.match(engine, /text-during-probable-silence/);
assert.match(engine, /if selected\["quality"\]\["suspicious"\]/);
assert.match(engine, /"quality_records": quality_records/);

assert.match(pipeline, /source == destination/);
assert.match(pipeline, /transcription working copy may never overwrite/);
assert.match(pipeline, /from audio_enhancement import enhance_speech_pcm/);
assert.match(pipeline, /fallback_from/);
assert.match(pipeline, /CANONICAL_CLEANUP_MODES = \{"off", "balanced", "strong"\}/);
assert.match(pipeline, /"automatic": "balanced"/);
assert.match(pipeline, /stationary_noise_attenuation_db/);
assert.match(pipeline, /source_md5_after != source_md5_before/);
assert.match(enhancement, /speech-aware-spectral-v1/);
assert.match(enhancement, /MAX_SPECTRAL_BATCH_FRAMES = 256/);
assert.match(enhancement, /vad_trimming": False/);
assert.match(enhancement, /speech_preservation_floor/);
assert.match(enhancement, /_attenuate_isolated_transients/);
assert.match(enhancement, /sustained_speech/);
assert.match(enhancement, /_bounded_speech_gain/);
assert.match(enhancement, /Strong cleanup can affect difficult or overlapping speech/);

assert.match(jobs, /os\.replace\(temporary, path\)/);
assert.match(jobs, /mark_unfinished_interrupted/);
assert.match(jobs, /COMPLETED_RETENTION_SECONDS = 7 \* 24/);
assert.match(jobs, /pairing_code/);
assert.match(jobs, /def contains_secret_key/);
assert.match(server, /@app\.post\("\/jobs\/\{job_id\}\/resume"/);
assert.match(server, /@app\.post\("\/jobs\/\{job_id\}\/retry-current"/);
assert.match(server, /@app\.post\("\/jobs\/\{job_id\}\/cancel"/);
assert.match(server, /cancel_requested/);
assert.match(server, /elapsed_seconds/);
assert.match(server, /eta_seconds/);
assert.match(server, /@app\.post\("\/enhancements"/);
assert.match(server, /@app\.get\("\/enhancements\/\{job_id\}\/audio"/);
assert.match(server, /write_enhanced_copy/);
assert.match(server, /owner_host/);
assert.match(server, /JOB_STORE\.write/);
assert.match(server, /partial_segments/);
assert.match(server, /STALL_TIMEOUT_SECONDS/);
assert.doesNotMatch(server, /JOB_RETENTION_SECONDS = 60 \* 60/);

assert.match(expoComputer, /existingJobId/);
assert.match(expoComputer, /computerJobStatus/);
assert.match(expoComputer, /resumeComputerJob/);
assert.match(expoComputer, /cancelComputerJob/);
assert.match(expoComputer, /retryCurrentComputerSection/);
assert.match(expoComputer, /generateEnhancedOnComputer/);
assert.match(expoComputer, /downloadEnhancedFromComputer/);
assert.match(expoComputer, /Windows now owns this transcription job/);
assert.match(expoComputer, /Estimating remaining time/);
assert.match(expoApp, /windowsTranscriptionJob/);
assert.match(expoApp, /ready-to-apply/);
assert.match(expoApp, /Derived copy — safe to regenerate or delete/);
assert.match(expoApp, /Retry current section/);
assert.match(expoApp, /Cancel safely/);
assert.match(expoApp, /ORIGINAL RECORDING/);
assert.match(expoApp, /Protected — never modified/);
assert.match(expoApp, /ENHANCED FOR TRANSCRIPTION/);
assert.match(expoApp, /Delete Enhanced Copy/);
assert.match(expoApp, /Transcribe Original/);
assert.match(expoApp, /Transcribe Enhanced/);
assert.match(expoApp, /enhancement: effectiveSource === 'original' \? cleanupMode : 'off'/);
assert.match(expoApp, /bounded quality fallback/);
assert.match(expoStorage, /SecureStore\.setItemAsync/);
assert.match(expoStorage, /installEnhancedAudioFile/);
assert.match(expoStorage, /deleteEnhancedAudioCopy/);
assert.match(expoStorage, /ensureDerivedAudioDirectory/);
assert.doesNotMatch(expoStorage, /computerToken:\s*computerToken/);
assert.match(audioDerivatives, /timestampReference: 'original'/);
assert.match(audioDerivatives, /assertOriginalIntegrity/);
assert.match(audioDerivatives, /currentEnhancedAudio/);

assert.match(phone, /WINDOW_SECONDS = 90/);
assert.match(phone, /WINDOW_WATCHDOG_MS/);
assert.match(phone, /onCheckpoint/);
assert.match(phone, /blob\.arrayBuffer\(\)/);
assert.match(webDetail, /decode the whole recording into PCM/);
assert.match(webDetail, /lecture\.duration > 30 \* 60/);
assert.match(webDetail, /Derived transcription cleanup/);
assert.match(webDetail, /Retry current section/);
assert.match(webDetail, /Cancel safely/);
assert.match(transcriptionClient, /generateNotes\?: boolean/);
assert.match(transcriptionClient, /completeTranscriptNotes/);
assert.match(transcriptionClient, /Estimating remaining time/);
assert.match(webDetail, /generateNotes: false/);
assert.match(expoApp, /SOURCE TRANSCRIPT READY · saved locally/);
assert.ok(expoApp.indexOf('await upsertLecture(updated)') < expoApp.indexOf('updated = applyStudyPack(updated)'), 'Expo must persist the source transcript before optional study generation');
assert.match(server, /Not enough free disk space/);
assert.match(webDb, /windowsTranscriptionJob/);
assert.match(webDb, /phoneTranscriptionCheckpoint/);

assert.match(launcher, /WindowStyle Hidden/);
assert.doesNotMatch(launcher, /KEEP OPEN/i);

console.log('✓ bounded Windows jobs, cleanup modes, cancel/retry/resume, source-first persistence, stall recovery, and truthful browser limits are present');
